### ISSUE TITLE
Tooltip doesn't update on rename

### ISSUE THREAD

**Issue by kevinsawicki** [atom/tabs#12]
Old path is still shown when hovering over renamed buffer

**Comment by lee-dohm** [comment]
See https://github.com/atom/atom/issues/13402 for steps to reproduce the problem. I reproduced this using Atom v1.12.7 on Mac OS X 10.12.2.

**Comment by FezVrasta** [comment]
I have a similar problem but when I rename a folder.

Example:

have a folder with few files inside
open those files
rename the folder
the tabs of these files remain open and point to the old folder name
This makes me edit the old files instead of the new ones and when I save, I re-create the old folder, actually duplicating the file... This is very annoying.

**Comment by ungb** [comment]
The above repro steps provided by @FezVrasta, I can repro the issue.
