### ISSUE TITLE
Empty dblclick should always create a new file

### ISSUE THREAD

**Issue by skogshjort** [atom/tabs#130]
Double clicking an empty part of the tabs area should always create a new tab with an empty file. Currently this behaviour only works when one or more tabs are open, not when no tabs are active.

**Comment by jerone** [comment]
The issue is that when there are no tabs (read; there's no texteditor), [background-tips](https://github.com/atom/background-tips) will appear. Aldo in DOM they are below tab-bar, the position is above the tab-bar. Not allowing events to go through.

This could be solved in two ways:

1. Move the tab-bar above the background-tips. But this might conflict with themes.
2. Add CSS property [`pointer-events: none;`](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) to allow events to go through.

The last solution I submitted to the [background-tips package](https://github.com/atom/background-tips): https://github.com/atom/background-tips/pull/16
