### ISSUE TITLE
Files opened via fuzzy finder should not be temporary

### ISSUE THREAD

**Issue by brendanblackwood** [atom/tabs#164]
This is more of an enhancement (possibly) than a bug. If "Use Preview Tabs" is enabled and I open a file via fuzzy finder and don't modify it or double click on the tab, it is a preview tab and will be replaced by the next file opened. I guess I'm used to this behavior coming from SublimeText, but that doesn't really make it "better". What would people think of adding an option for this behavior? Much like the single vs double click in #156

**Comment by AdamBuczynski** [comment]
+1 

I actually think this is a bug. When using the fuzzy finder, the file should definitely remain open as it used to before, because you are most likely looking for a specific file to work in.

In addition, if you're already pressing the keyboard commands to open the fuzzy finder, it's no bit detour to press CMD-W to close the window again if you don't want it after all. Whereas having to switch to your mouse to double click the tab to keep it open is just a hassle.

This is particularly irritating when you want to open several files to work in using fuzzy finder.

**Comment by brendanblackwood** [comment]
Looking at the other tickets around this (#156, #170, #172), it's looking like it might be good to be able to specify which actions should open a preview and which should not. I like the preview functionality a lot, but for me, there are more cases where I don't want it than where I do.

**Comment by AdamBuczynski** [comment]
Agree that being able to specify when preview tabs are triggered and when not would probably be the most flexible solution, allowing everyone to configure it as they like.

**Comment by bronson** [comment]
I'd like the tab to become permanent if I navigate in a file (not scrolling, but if I move the cursor even a single character).  Without this, I find using preview tabs requires too much double-clicking to manually force a tab I'm interested in to stick around.

(wonder if I could find some events that would allow me to write a package that does this...?)

**Comment by nlenkowski** [comment]
This! I love tab previews in conjunction with the sidebar, it's nice to be able to preview lots of files quickly. However, opening multiple files in sequence from the fuzzy finder is a real pain with tab previews enabled. Each time I open a file I then have to double click its tab before opening the next, lest the tab be replaced by the next file opened.

**Comment by adambuczynski** [comment]
> However, opening multiple files in sequence from the fuzzy finder is a real pain with tab previews enabled. Each time I open a file I then have to double click its tab before opening the next, lest the tab be replaced by the next file opened.

Yeah, it's becoming quite a pain, I forgot how it feels to be able to work without having to double click every other tab :P

I was hoping this would get fixed as a part of the quality initiative, as it was listed as a todo item there, but unfortunately it seems to be quite low on the radar.

**Comment by nlenkowski** [comment]
Yeah, I saw that was in the quality initiative, bummer it didn't get fixed yet. Hopefully it will be on deck soon.

**Comment by lodev09** [comment]
+10000

**Comment by ssorallen** [comment]
The notion of a "preview" view should be moved to the `atom.workspace.open` API so consumers like fuzzy-finder can opt out of the preview feature regardless of the setting. This is the same as Sublime Text [`sublime.Window::open_file`](https://www.sublimetext.com/docs/3/api_reference.html#sublime.Window) function, which uses the preview view only if the `sublime.TRANSIENT` flag is set. This would simplify integration with other packages as well, allowing them to open files as permanent or preview, instead of the tabs package having to reach into the DOM of other packages like 'tree-view'.

**Comment by dbroadhurst** [comment]
+1 personally just like to see temporary files just coming from the tree selector since I'm generally just browsing

**Comment by benogle** [comment]
This is fixed on master and the 1.5.x line which is in beta now. See https://github.com/atom/atom/issues/9165 for more information.

**Comment by adambuczynski** [comment]
:+1:

**Comment by brendanblackwood** [comment]
Thanks guys! :+1:
