### ISSUE TITLE
"Enable VCS Coloring" does not work with symbolic links

### ISSUE THREAD

**Issue by kankaristo** [atom/tabs#182]
The "Enable VCS Coloring" feature seems to break if the project directory or any of its parent directories is a symbolic link.

I have most of my (larger) projects on an external drive, because my main hard drive is a small SSD. I have symbolic links from inside my home directory to the external drive.

If I open a directory from the external drive, the tab coloring works fine. If I open the same directory through a symbolic link, the tab text color is always the same, regardless of the VCS (Git) status of the file.

The tab titles are colored correctly with the git-tab-status package, but not using "Enable VCS Coloring". The file names are also colored correctly in tree-view.

- Ubuntu 14.04.2 LTS
- Atom 0.210.0
- tabs 0.81.0

**Comment by acontreras89** [comment]
I've been able to reproduce this error.
I'm already looking into it. `getRepoForPath` ([here](https://github.com/atom/tabs/blob/master/lib/tab-view.coffee#L210)) does not find the repository for the file if any of its parent folders is a symbolic link.
To fix that, `atom.project.getDirectories` should be used instead of `atom.project.getPaths` (which returns the real paths for the projects.)

.. Working on it

**Comment by acontreras89** [comment]
@kankaristo can you check this issue https://github.com/atom/tree-view/issues/484 and let me know if you are able to reproduce it? 

It might be closely related to the problem we're addressing here.

**Comment by acontreras89** [comment]
Created https://github.com/atom/tabs/pull/184 to fix this problem.
