### ISSUE TITLE
when searching a file the tab will in preview mode

### ISSUE THREAD

**Issue by dioxmio** [atom/tabs#233]
It's just a suggestion: 

when searching a file (and **Use Preview Tabs** activated) the file will be open in preview mode. It might come in handy to have an option to configure that behavior. Some people might like to have this file opened in a new tab.  

What do you think? I'm not sure about the naming. Maybe something like: **Use Preview Tabs on Search**

I can volunteer to do this feature if accepted :)

**Comment by gfviegas** [comment]
You mean when you use **CTRL + P** and open a file? For me, the file opens in preview mode and it's really annoying... I wish I could have the same behavior Sublime Text has, as I think ctrl+P is a search and OPEN a file.
It bothers me because when I already have a file in preview, when I click in tree view for example, and then I open another in ctrl+P it closes the one in preview, so I have to double click the one open and re-open the another it was already in preview mode. Wish that preview mode only be applied by clicking in tree view tho.

**Comment by dioxmio** [comment]
@gfviegas that's exactly what I mean :+1:

**Comment by gfviegas** [comment]
So.. +1!

**Comment by Dremora** [comment]
I think preview mode should only apply when files are opened from the file tree. In any other scenario (opening from search results, opening via `Command-P`) it should just open. There's no way to double-click on something in those UIs to opt-out of preview mode. I'd also argue that this behaviour shouldn't be configurable — at least not until users start asking for it, which might not happen.

**Comment by aribeiroc** [comment]
+1! is really needed :)

**Comment by BinaryMuse** [comment]
This behavior has changed with the pending pane item API changes from atom/atom#10959 and related change sets, and is available in 1.6.0-beta7 and beyond.
