### ISSUE TITLE
Close all tabs does not work

### ISSUE THREAD

**Issue by kafeltz** [atom/tabs#248]
In (File -> Close All Tabs) do nothing if a tab is not selected (focused).

To un-focus a tab, just click in some file in tree-view and go right in (File -> Close All  Tabs).

You have to click anywhere in any tab to gain focus before going in Close All Tabs.

**Comment by iKlsR** [comment]
Able to reproduce this in 1.4.

**Comment by stanfieldr** [comment]
I think this is an issue with the way commands are designed. They are just using the active element [here](https://github.com/atom/atom/blob/c5a76d4a7d9b7de9c78a534091a1b775bc5e9c9a/src/atom-environment.coffee#L932) when calling menu commands. And then in the command-registry uses the idea of event delegation. So since the tree view never bubbles the event through the pane, it is never notified.

**Comment by lee-dohm** [comment]
Fixed by #325.

**Comment by kafeltz** [comment]
Super cool
