### ISSUE TITLE
Tab scrolling stopped working

### ISSUE THREAD

**Issue by puranjayjain** [atom/tabs#311]
**UPDATED**
Repro:
1. Open Atom.  
2. Open a bunch of tabs like 3-5
3. Open settings (on mac: `cmd+,`)  (or `ctrl + ,` on linux and windows)
4. Go to `Packages` and look for tabs package.
5. Change the settings to true and try to use the mouse wheel to scroll on the tabs.

Expected: works

Actual:
Windows: doesn't work
Mac: doesn't work
Linux: Works

Changing the setting in `Packages -> Tabs` in settings views doesn't do anything for any OS's

see screenshot:

macOS(same behavior as windows):
![macscroll](https://user-images.githubusercontent.com/5624870/31522336-1cf511c8-af62-11e7-9342-47dd878dcfe0.gif)

Ubuntu(even if you set to false it works):
![linux](https://user-images.githubusercontent.com/5624870/31522344-23474078-af62-11e7-9cfa-3caba02c359a.gif)

___

Scrolling over tabs no longer changes the tab..

Tried on:
WIndows 10 Pro and Enterprise (x64)
Atom 1.7.2 and 1.8.0-beta2

With all the three possible settings: true, false and platform.

**Comment by 50Wliu** [comment]
Cannot reproduce on Ubuntu 16.04, Atom 1.9.0-dev-9175194.

**Comment by FlorianM1234** [comment]
Works for me only with shift + mouse scroll over Tab bar on Windows (Platform setting)

**Comment by 50Wliu** [comment]
I can't reproduce this on Atom 1.9.0-dev-7b2f049, Windows 10 x64.

**Comment by DarkNami** [comment]
After upgrade to Atom 1.8.0, I can't scroll tabs, too.
OS: Windows 7 Pro (x64)

**Comment by Parziphal** [comment]
I'm using Windows 10 Pro and Atom 1.8.0 (and I'm new to Atom), and I have been annoyed because I couldn't scroll through tabs (since I'm new I don't know if Atom has always been like this). I found out right now, by FlorianM1234's comment, that I can scroll through tabs using Shift+Mouse scroll.

![image](https://cloud.githubusercontent.com/assets/5176023/15937243/a35fc624-2e33-11e6-89c1-7e737bc8690e.png)

In this image, there are more tabs after `app.ts` but I can't tell there are more. Something like Notepad++'s tabs would be nice (the arrow buttons):

![image](https://cloud.githubusercontent.com/assets/5176023/15937424/7a8d3366-2e34-11e6-8a9b-5d7cd3afe437.png)

Issue #136 is more than a year old and an indicator to know there are hidden tabs hasn't been added. Am I missing something about how to know I have more tabs to the left or to the right?

**Comment by Ben3eeE** [comment]
> Scrolling over tabs no longer changes the tab..

It is not possible to set the tab scrolling value because of https://github.com/atom/tabs/issues/284. If I work around this problem then scrolling over the tab bar to change the tab still works.

@Parziphal What you report is covered by https://github.com/atom/tabs/issues/137

**Comment by Area6** [comment]
same here

**Comment by Ben3eeE** [comment]
I can reproduce this using Atom 1.20. The `Tab Scrolling` setting does not work.

**Comment by ungb** [comment]
I've tested on Linux and Mac.  I can see it working on Ubuntu, but not on Mac

**Comment by joedf** [comment]
Not working at all for me (true, platform, false)... Win10 x64, atom 1.22.1

**Comment by 50Wliu** [comment]
Ok, so this is a settings-view issue.  If I force the setting to true in config.cson, then scrolling works as expected for me, but changing it through the UI has no effect.

**Comment by rsese** [comment]
@Ben3eeE @50Wliu - we were going through some older issues and for this one, we didn't have a mouse with a scroll wheel handy, can either of you still reproduce?

**Comment by Ben3eeE** [comment]
I can still reproduce

**Comment by deadlyfingers** [comment]
Still an issue on Mac, but setting 'true' fixes it.

**Comment by rcxcob2016** [comment]
Still an issue on windows, had to put setting on 'true' instead of 'platform'.
