### ISSUE TITLE
Pending files should not be default file opening behavior

### ISSUE THREAD

**Issue by Bango1999** [atom/tabs#313]
I'd like to see a single-click to open a file normally, and double click to open as a pending file. As per Issue #250, quite a few people feel that the current default-to-pending tab behavior is unexpected.  I also agree.

This would negate the necessity for double clicking on an open tab/editing the file to de-pend it and make it a normal tab.

My reasoning behind this is, many times I need to open multiple files for viewing at the same time.

**Comment by lee-dohm** [comment]
Thanks very much for your feedback. We believe we've struck the right balance with the current design. We know that some people disagree with us. The great thing about Atom is that it is extensible at a very deep level. So someone created the [single-click-open package](https://atom.io/packages/single-click-open) that works with the pending files setting to make it so that you can open files in non-pending mode with a single click. You may want to check it out.

Thanks for your passion and interest in Atom!
