### ISSUE TITLE
Pending italic/italicized file/tab/pane should not force every developer to double click to open new (multiple) files

### ISSUE THREAD

**Issue by lope** [atom/tabs#366]
Please excuse the verbosity of the title, I wanted to ensure that other people experiencing this extremely frustrating issue will be able to find this issue. Because when I experienced it for the first time after upgrading to the new version of Atom, I was stuck for 10-15 mins trying all sorts of tricks to try get Atom to be able to open multiple files again. I thought Atom was broken. Luckily someone on IRC knew the answer.

@lee-dohm please read the entire issue rather than dismissing this easily as you have #313 

This issue is similar in sentiment to #313, but my assertion is different.
**I assert that there should be an option to swap the single and double click behavior actions of either previewing or opening a file.**

**Different people working with different technologies have different types of workflows.**

If you want to have a code editor and a large community you can't force everyone to double click files just because that's the way **you** like it.

I generally don't need to preview files because I generally know what's in them. If I open a file, 90%+ of the time it's because I want to work on it. So for me it means the preview tab is not totally useless, but it's an edge case in my workflow.

The option provided "Allow pending **pain** items" is not sufficient. Because when I uncheck that, all it does is it disables the single click from opening a pending tab. I still have to double click to open files which is **just as inconvenient** as with the option checked.

**IMO the disabling of pending tabs is not useful at all**, and not a solution to the diverging needs/preferences on this issue.

What would be useful is an option to swap the single/double click behavior to fit with the individual developer's workflow. Do you need to mostly work on files, or just preview them. That should determine how many clicks you should have to make get the operation you want.

**A developer's most commonly intended action should be accomplished with 1 click.**

**We should not need to install an extra package to get normal functionality out of a code editor**.

**Editing files is the main purpose of a code editor**, making it impossible to open a file with 1 click, via the standard options is not a step forward. It's a step backwards.

As a minor side note, in my opinion the default should be that single click opens a file, and double click previews. **But really that default option doesn't matter much compared to actually having the ability to function efficiently** once you've set the available options to your preference.

Related sentiments #250 

@lee-dohm has suggested installing the [single-click-open](https://atom.io/packages/single-click-open) package as a workaround to this problem. Reluctantly I tried it out now, but it's not a solution to this issue. Because it makes previewing a file impossible. I do not assert that previewing files is useless, but rather that it's an edge case for some developers (like me).

PS: Adding a middle click option would also be nice.
So ideally the options would be something like this (select boxes)
Left click action: Open file | Preview File
Dbl click action:  Open file | Preview File
Middle click action:  Open file | Preview File

Then any dev can set the stuff to their heart's content.

**Comment by adrianlafond** [comment]
I could not agree more with this entire post.

**Comment by lee-dohm** [comment]
@lope Thanks very much for your well thought out and reasoned post. I can tell that you're quite frustrated by this behavior.

> you can't force everyone to double click files just because that's the way **you** like it.

We're not forcing anyone to do anything. This is open source software. One of the basic tenets of open source software is that you have the freedom to change it in any way you like. Everyone is welcome to fork the relevant repositories and change the software however they wish. Additionally, the Atom maintainers have the freedom to say no to suggestions or feature requests and to politely decline pull requests if that is what we think is best for the project.

We don't believe that adding a bunch of options for this behavior is going to be beneficial for the majority of people using Atom. Because of this, we aren't going to be implementing this proposed change. We also don't feel that supporting and maintaining the complexity created by the proposal is something that would be worth the cost, so we won't be accepting PRs that implement this either.

Thank you again for the effort you put into explaining your position and your ideas.
