### ISSUE TITLE
Text jumps when hovering the tab bar

### ISSUE THREAD

**Issue by lloiser** [atom/tabs#394]
OS: OSX El Capitan (10.11.6)
Atom: 1.11.2
Theme: one-dark-ui (with layout mode "compact" and tab sizing "minimum")
Syntax: https://atom.io/themes/monokai-seti 
(I'm also using https://atom.io/packages/file-icons)

![jumpy](https://cloud.githubusercontent.com/assets/3003233/19961989/c3beefda-a1b5-11e6-842c-3cb8bda01a2e.gif)

Having several tabs open causes some tab texts (and icons) to jump slightly when you hover the tab bar. This is caused by rounding issues happening here: https://github.com/atom/tabs/blob/master/lib/tab-bar-view.coffee#L490. Removing the `toFixed(2)` fixes the rounding issue and therefor the jumping.

**Comment by Ben3eeE** [comment]
Can you reproduce this in safe mode `atom --safe`?

**Comment by lloiser** [comment]
It works in `atom --safe` because I'm not using the mentioned plugins/themes. When I activate those plugins/themes I can see this issue.
Atom 1.12 does not fix it.

**Comment by thomasjo** [comment]
This definitely looks like a bug in file-icons. That package also has some alignment issue related to tree-view. I'm betting on this being an alignment issue caused by file-icons.

**Comment by mnquintana** [comment]
Thanks for contributing!

It seems that this is being caused by the [file-icons package](https://atom.io/packages/file-icons), not Atom itself. It may be that there's still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
