### ISSUE TITLE
Hotkey support to toggle tabs panel

### ISSUE THREAD

**Issue by L1Q** [atom/tabs#415]
Is there a way to toggle tabs panel other then going to settings menu, finding the package in a list and manually disabling/enabling it?

I need a way to bind tabs panel toggling to a key combo.

**Comment by rsese** [comment]
Thanks for reaching out!

I don't believe this is possible but there may be a community package that does what you want?

https://atom.io/packages/search?q=toggle%20tabs

But because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
