### ISSUE TITLE
Floating tabs

### ISSUE THREAD

**Issue by JosephDAM** [atom/tabs#432]
Hi,

I was wondering if light floating tabs was something you guys have in mind, or if it already is implemented.
I don't necessarily mean drag&drop to open a new window feature, I already saw #39 . What I mean is a floating editor for files, one that does not load a full new window. Something like netbeans float/dock functionallity.
Waiting a few seconds for a new window to open is not the end of the world, but a light floating editor that actually depends on the main window would be a really nice feature :)

Best regards

P.S.: If there is a better communication channel for questions like this please let me know!

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
