### ISSUE TITLE
Uncaught Error: Adding a pane item with URI 'undefined' that has already been destroyed

### ISSUE THREAD

**Issue by rmethlie** [atom/tabs#453]
[Enter steps to reproduce:]

1. Open "Source Preview" (opens in split pane)
2. Drag Preview window to left pane.

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [tabs](https://github.com/atom/tabs) package 0.106.0

### Stack Trace

Uncaught Error: Adding a pane item with URI 'undefined' that has already been destroyed

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:493

Error: Adding a pane item with URI 'undefined' that has already been destroyed
    at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:493:1)
    at Pane.module.exports.Pane.moveItemToPane (/Applications/Atom.app/Contents/Resources/app/src/pane.js:655:1)
    at TabBarView.module.exports.TabBarView.moveItemBetweenPanes (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:757:1)
    at TabBarView.module.exports.TabBarView.onDrop (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:643:1)
```

### Commands

```
     -1:25.5.0 core:select-down (input.hidden-input)
     -1:24.2.0 command-palette:toggle (input.hidden-input)
     -1:23.2.0 core:confirm (input.hidden-input)
     -1:23.2.0 source-preview:toggle (input.hidden-input)
     -0:46.3.0 command-palette:toggle (input.hidden-input)
     -0:45.3.0 core:confirm (input.hidden-input)
     -0:45.3.0 source-preview:toggle (input.hidden-input)
     -0:18.9.0 editor:consolidate-selections (input.hidden-input)
     -0:18.9.0 core:cancel (input.hidden-input)
     -0:18.7.0 editor:consolidate-selections (input.hidden-input)
     -0:18.7.0 core:cancel (input.hidden-input)
     -0:18.6.0 editor:consolidate-selections (input.hidden-input)
     -0:18.6.0 core:cancel (input.hidden-input)
 20x -0:15.5.0 core:move-down (input.hidden-input)
 34x -0:14.2.0 core:move-up (input.hidden-input)
 34x -0:11.2.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.1 
coffee-compile 0.26.0 
intentions 1.1.2 
jslint 1.5.1 
language-babel 2.65.0 
linter 2.1.4 
linter-eslint 8.2.1 
linter-ui-default 1.2.4 
markdown-scroll-sync 2.1.2 
markdown-writer 2.6.5 
platformio-ide-terminal 2.5.1 
pretty-json 1.6.3 
source-preview 0.5.1 
terminal-plus 0.14.5 
xml-formatter 0.10.0 
```

**Comment by rsese** [comment]
I can reproduce with source-preview and your steps to reproduce - the stack trace is slightly different than https://github.com/atom/tabs/issues/444 so I'll leave this as a separate issue for now.

**Comment by rsese** [comment]
Sorry, poking at it again with the advice of another maintainer, I tried a couple of similar packages that open another pane (Markdown preview and find and replace) and couldn't reproduce with either of them.  In this case since the error is specific to using source preview, a good next step would be to report this to the [source-preview](https://github.com/aki77/atom-source-preview/) maintainers.

It may be that there is still a bug in Atom and if so, we'll need the maintainer of the package to help track that down. You can file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by rmethlie** [comment]
Thanks for the quick look.  I will let source-preview maintainers know.
