### ISSUE TITLE
Middle click doesn't close tab

### ISSUE THREAD

**Issue by AlexWayfer** [atom/tabs#545]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. Click on tab via middle mouse button (wheel)

**Expected behavior:** Tab is closing.

**Actual behavior:** Tab isn't closing.

**Reproduces how often:** 100%

### Versions

Arch Linux.

```
> atom --version
apAtom    : 1.32.2
Electron: 3.0.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

> apm --version
apm  2.1.3
npm  6.4.1
node 11.4.0 x64
atom 1.32.2
python 2.7.15
git 2.20.0
```

### Additional Information

Probably it appeared after upgrade to Electron 3.

Atom doesn't start with Electron 2 now.

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!
