### ISSUE TITLE
Possible to increase tab close X for touchscreens?

### ISSUE THREAD

**Issue by ljsinclair** [atom/tabs#558]
Hi there,
Want to ask if it's possible to scale the close button on tabs for touchscreens like Surface Pro. I often find my stubby fingers miss the button and it takes 3-4 goes to close a tab.

The close button in current Firefox is an example, and seem to work first time every time

Thanks for reading and have a great day :)

L.

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

And as mentioned in the issue template, we're unlikely to prioritize feature requests right now and we strongly prefer that people take advantage of Atom's customizability where possible.  For example, you can play around with the styles to see if that helps (https://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks):

```css
.tab-bar .tab .close-icon {
  top: 0.2em;
  width: 3em;
  height: 2em;
  line-height: 2;
}
```
