### ISSUE TITLE
Differentiating tabs title for opened files with the same name but in different folders

### ISSUE THREAD

**Issue by matteo-webdev** [atom/tabs#57]
When different files with the same name (but in different folders) are opened there is no easy way to tell which ones is which by looking at the title in the tabs.
In Sublime Text this differentiation is achieved by appending the path to the file (from the root of the project) to the names of the same-named files in the tab.
It would be nice to replicate this feature in Atom.

I attach a pair of screenshot to better explain the matter.

here is the issue in atom:
![samefiles-in-atom_ss](https://cloud.githubusercontent.com/assets/1353596/3052480/577eaa68-e19b-11e3-974d-14b82ce985a8.png)

 and here is the same scenario in sublime:
![samefiles-in-sublime_ss](https://cloud.githubusercontent.com/assets/1353596/3052482/6432535e-e19b-11e3-93c9-5b6968c01994.png)

**Comment by brendanfalkowski** [comment]
Showing a longer snippet from the end of the path is more useful than showing the beginning + end. In practice I see the exact same thing for all tab titles (also a problem in screenshots above).

When the path to files is not very shallow (1-2 folders) they're not distinguishable. It would be more effective if there are multiple tabs with the same file name to show the full path from the right side. That would highlight the most specific part of the path (not the least specific, as today).

Attached screenshot from my project with better tab titles in red. It would be even better if the difference was bold, so that stands out.

![artboard](https://cloud.githubusercontent.com/assets/214924/8315002/47dad038-19bb-11e5-8fec-84b88b6959b4.png)

**Comment by davibe** [comment]
I am developing large react+redux app where i organize files by feature rather than file type. Therefore i have similar structure

```
components/Component1/view.js
components/Component1/reducer.js
components/Component1/action.js
components/Component1/style.less

components/Component2/view.js
components/Component2/reducer.js
components/Component2/action.js
components/Component2/style.less

...
```

As you can imagine in this case the best option would be to show "as much path tokens as needed to make the tab name unique starting from the filename going upwards in the path tree". Therefore my tab names could be i.e.

"Component1/index.js", "Component2/index.js"

or

"index.js - Component1", "index.js - Component2"

This would result in snorter and more readable names i think.

Then if the "common" path is very long the shortening you have already done looks ok.
